### ISSUE TITLE
Android application shows "Requiring unknown module "react-native-android-sqllite"

### ISSUE THREAD

**Issue by ghost** [jbrodriguez/rn-sqlite#1]

**Comment by jbrodriguez** [comment]
Hi @shafips, is it possible that you were using react-native-android-sqlite, switched to rn-sqlite and there's a require('react-native-android-sqlite') or import from 'react-native-android-sqlite' somewhere in your code ?

I'm using this library in a brand new project and I'm not getting this error.

**Comment by ghost** [comment]
I have followed the instructions and i used rnpm option to install.
 i used this imprt. `import SQLite from 'react-native-android-sqlite';`

**Comment by jbrodriguez** [comment]
I see it now. I have to update the instructions.

The correct import is 
`import SQLite from 'rn-sqlite`

Thanks for bringing my attention to this, @shafips !

**Comment by ghost** [comment]
Thanks @jbrodriguez , init is working now.
